image: python:3.10

stages:
  - test

before_script:
  - cd C:\Users\bezborodnikov\Desktop\jobs\testing-hs-boards
  - .\venv\Scripts\activate
  - pip install -r requirements.txt
  - pip install pytest-html

.test_template:
  stage: test
  script:
    - |
      if ($env:TEST_SUITE -eq "first_test") {
        pytest tests/test_first.py
      } elseif ($env:TEST_SUITE -eq "second_test") {
        pytest tests/test_second.py
      } elseif ($env:TEST_SUITE -eq "all_tests") {
        pytest tests/test_first.py
        pytest tests/test_second.py
      }
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
  tags:
    - hs

test_first:
  extends: .test_template
  variables:
    TEST_SUITE: first_test

test_second:
  extends: .test_template
  variables:
    TEST_SUITE: second_test

test_all:
  extends: .test_template
  variables:
    TEST_SUITE: all_tests
